# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/williammeaton/Desktop/closedFrameworks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/williammeaton/Desktop/closedFrameworks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/williammeaton/Desktop/closedFrameworks/CMakeFiles /Users/williammeaton/Desktop/closedFrameworks/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/williammeaton/Desktop/closedFrameworks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named closedFrameworks

# Build rule for target.
closedFrameworks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 closedFrameworks
.PHONY : closedFrameworks

# fast build rule for target.
closedFrameworks/fast:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/build
.PHONY : closedFrameworks/fast

CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

cfsrc/Animator.o: cfsrc/Animator.cpp.o

.PHONY : cfsrc/Animator.o

# target to build an object file
cfsrc/Animator.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Animator.cpp.o
.PHONY : cfsrc/Animator.cpp.o

cfsrc/Animator.i: cfsrc/Animator.cpp.i

.PHONY : cfsrc/Animator.i

# target to preprocess a source file
cfsrc/Animator.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Animator.cpp.i
.PHONY : cfsrc/Animator.cpp.i

cfsrc/Animator.s: cfsrc/Animator.cpp.s

.PHONY : cfsrc/Animator.s

# target to generate assembly for a file
cfsrc/Animator.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Animator.cpp.s
.PHONY : cfsrc/Animator.cpp.s

cfsrc/BaseCore.o: cfsrc/BaseCore.cpp.o

.PHONY : cfsrc/BaseCore.o

# target to build an object file
cfsrc/BaseCore.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/BaseCore.cpp.o
.PHONY : cfsrc/BaseCore.cpp.o

cfsrc/BaseCore.i: cfsrc/BaseCore.cpp.i

.PHONY : cfsrc/BaseCore.i

# target to preprocess a source file
cfsrc/BaseCore.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/BaseCore.cpp.i
.PHONY : cfsrc/BaseCore.cpp.i

cfsrc/BaseCore.s: cfsrc/BaseCore.cpp.s

.PHONY : cfsrc/BaseCore.s

# target to generate assembly for a file
cfsrc/BaseCore.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/BaseCore.cpp.s
.PHONY : cfsrc/BaseCore.cpp.s

cfsrc/BoxCollider.o: cfsrc/BoxCollider.cpp.o

.PHONY : cfsrc/BoxCollider.o

# target to build an object file
cfsrc/BoxCollider.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/BoxCollider.cpp.o
.PHONY : cfsrc/BoxCollider.cpp.o

cfsrc/BoxCollider.i: cfsrc/BoxCollider.cpp.i

.PHONY : cfsrc/BoxCollider.i

# target to preprocess a source file
cfsrc/BoxCollider.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/BoxCollider.cpp.i
.PHONY : cfsrc/BoxCollider.cpp.i

cfsrc/BoxCollider.s: cfsrc/BoxCollider.cpp.s

.PHONY : cfsrc/BoxCollider.s

# target to generate assembly for a file
cfsrc/BoxCollider.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/BoxCollider.cpp.s
.PHONY : cfsrc/BoxCollider.cpp.s

cfsrc/Client.o: cfsrc/Client.cpp.o

.PHONY : cfsrc/Client.o

# target to build an object file
cfsrc/Client.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Client.cpp.o
.PHONY : cfsrc/Client.cpp.o

cfsrc/Client.i: cfsrc/Client.cpp.i

.PHONY : cfsrc/Client.i

# target to preprocess a source file
cfsrc/Client.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Client.cpp.i
.PHONY : cfsrc/Client.cpp.i

cfsrc/Client.s: cfsrc/Client.cpp.s

.PHONY : cfsrc/Client.s

# target to generate assembly for a file
cfsrc/Client.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Client.cpp.s
.PHONY : cfsrc/Client.cpp.s

cfsrc/Collider.o: cfsrc/Collider.cpp.o

.PHONY : cfsrc/Collider.o

# target to build an object file
cfsrc/Collider.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Collider.cpp.o
.PHONY : cfsrc/Collider.cpp.o

cfsrc/Collider.i: cfsrc/Collider.cpp.i

.PHONY : cfsrc/Collider.i

# target to preprocess a source file
cfsrc/Collider.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Collider.cpp.i
.PHONY : cfsrc/Collider.cpp.i

cfsrc/Collider.s: cfsrc/Collider.cpp.s

.PHONY : cfsrc/Collider.s

# target to generate assembly for a file
cfsrc/Collider.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Collider.cpp.s
.PHONY : cfsrc/Collider.cpp.s

cfsrc/Collision.o: cfsrc/Collision.cpp.o

.PHONY : cfsrc/Collision.o

# target to build an object file
cfsrc/Collision.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Collision.cpp.o
.PHONY : cfsrc/Collision.cpp.o

cfsrc/Collision.i: cfsrc/Collision.cpp.i

.PHONY : cfsrc/Collision.i

# target to preprocess a source file
cfsrc/Collision.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Collision.cpp.i
.PHONY : cfsrc/Collision.cpp.i

cfsrc/Collision.s: cfsrc/Collision.cpp.s

.PHONY : cfsrc/Collision.s

# target to generate assembly for a file
cfsrc/Collision.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Collision.cpp.s
.PHONY : cfsrc/Collision.cpp.s

cfsrc/Component.o: cfsrc/Component.cpp.o

.PHONY : cfsrc/Component.o

# target to build an object file
cfsrc/Component.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Component.cpp.o
.PHONY : cfsrc/Component.cpp.o

cfsrc/Component.i: cfsrc/Component.cpp.i

.PHONY : cfsrc/Component.i

# target to preprocess a source file
cfsrc/Component.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Component.cpp.i
.PHONY : cfsrc/Component.cpp.i

cfsrc/Component.s: cfsrc/Component.cpp.s

.PHONY : cfsrc/Component.s

# target to generate assembly for a file
cfsrc/Component.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Component.cpp.s
.PHONY : cfsrc/Component.cpp.s

cfsrc/Entity.o: cfsrc/Entity.cpp.o

.PHONY : cfsrc/Entity.o

# target to build an object file
cfsrc/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Entity.cpp.o
.PHONY : cfsrc/Entity.cpp.o

cfsrc/Entity.i: cfsrc/Entity.cpp.i

.PHONY : cfsrc/Entity.i

# target to preprocess a source file
cfsrc/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Entity.cpp.i
.PHONY : cfsrc/Entity.cpp.i

cfsrc/Entity.s: cfsrc/Entity.cpp.s

.PHONY : cfsrc/Entity.s

# target to generate assembly for a file
cfsrc/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Entity.cpp.s
.PHONY : cfsrc/Entity.cpp.s

cfsrc/Graphics.o: cfsrc/Graphics.cpp.o

.PHONY : cfsrc/Graphics.o

# target to build an object file
cfsrc/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Graphics.cpp.o
.PHONY : cfsrc/Graphics.cpp.o

cfsrc/Graphics.i: cfsrc/Graphics.cpp.i

.PHONY : cfsrc/Graphics.i

# target to preprocess a source file
cfsrc/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Graphics.cpp.i
.PHONY : cfsrc/Graphics.cpp.i

cfsrc/Graphics.s: cfsrc/Graphics.cpp.s

.PHONY : cfsrc/Graphics.s

# target to generate assembly for a file
cfsrc/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Graphics.cpp.s
.PHONY : cfsrc/Graphics.cpp.s

cfsrc/Image.o: cfsrc/Image.cpp.o

.PHONY : cfsrc/Image.o

# target to build an object file
cfsrc/Image.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Image.cpp.o
.PHONY : cfsrc/Image.cpp.o

cfsrc/Image.i: cfsrc/Image.cpp.i

.PHONY : cfsrc/Image.i

# target to preprocess a source file
cfsrc/Image.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Image.cpp.i
.PHONY : cfsrc/Image.cpp.i

cfsrc/Image.s: cfsrc/Image.cpp.s

.PHONY : cfsrc/Image.s

# target to generate assembly for a file
cfsrc/Image.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Image.cpp.s
.PHONY : cfsrc/Image.cpp.s

cfsrc/Input.o: cfsrc/Input.cpp.o

.PHONY : cfsrc/Input.o

# target to build an object file
cfsrc/Input.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Input.cpp.o
.PHONY : cfsrc/Input.cpp.o

cfsrc/Input.i: cfsrc/Input.cpp.i

.PHONY : cfsrc/Input.i

# target to preprocess a source file
cfsrc/Input.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Input.cpp.i
.PHONY : cfsrc/Input.cpp.i

cfsrc/Input.s: cfsrc/Input.cpp.s

.PHONY : cfsrc/Input.s

# target to generate assembly for a file
cfsrc/Input.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Input.cpp.s
.PHONY : cfsrc/Input.cpp.s

cfsrc/ResourceManager.o: cfsrc/ResourceManager.cpp.o

.PHONY : cfsrc/ResourceManager.o

# target to build an object file
cfsrc/ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/ResourceManager.cpp.o
.PHONY : cfsrc/ResourceManager.cpp.o

cfsrc/ResourceManager.i: cfsrc/ResourceManager.cpp.i

.PHONY : cfsrc/ResourceManager.i

# target to preprocess a source file
cfsrc/ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/ResourceManager.cpp.i
.PHONY : cfsrc/ResourceManager.cpp.i

cfsrc/ResourceManager.s: cfsrc/ResourceManager.cpp.s

.PHONY : cfsrc/ResourceManager.s

# target to generate assembly for a file
cfsrc/ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/ResourceManager.cpp.s
.PHONY : cfsrc/ResourceManager.cpp.s

cfsrc/RigidBody.o: cfsrc/RigidBody.cpp.o

.PHONY : cfsrc/RigidBody.o

# target to build an object file
cfsrc/RigidBody.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/RigidBody.cpp.o
.PHONY : cfsrc/RigidBody.cpp.o

cfsrc/RigidBody.i: cfsrc/RigidBody.cpp.i

.PHONY : cfsrc/RigidBody.i

# target to preprocess a source file
cfsrc/RigidBody.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/RigidBody.cpp.i
.PHONY : cfsrc/RigidBody.cpp.i

cfsrc/RigidBody.s: cfsrc/RigidBody.cpp.s

.PHONY : cfsrc/RigidBody.s

# target to generate assembly for a file
cfsrc/RigidBody.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/RigidBody.cpp.s
.PHONY : cfsrc/RigidBody.cpp.s

cfsrc/Runner.o: cfsrc/Runner.cpp.o

.PHONY : cfsrc/Runner.o

# target to build an object file
cfsrc/Runner.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Runner.cpp.o
.PHONY : cfsrc/Runner.cpp.o

cfsrc/Runner.i: cfsrc/Runner.cpp.i

.PHONY : cfsrc/Runner.i

# target to preprocess a source file
cfsrc/Runner.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Runner.cpp.i
.PHONY : cfsrc/Runner.cpp.i

cfsrc/Runner.s: cfsrc/Runner.cpp.s

.PHONY : cfsrc/Runner.s

# target to generate assembly for a file
cfsrc/Runner.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Runner.cpp.s
.PHONY : cfsrc/Runner.cpp.s

cfsrc/Scene.o: cfsrc/Scene.cpp.o

.PHONY : cfsrc/Scene.o

# target to build an object file
cfsrc/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Scene.cpp.o
.PHONY : cfsrc/Scene.cpp.o

cfsrc/Scene.i: cfsrc/Scene.cpp.i

.PHONY : cfsrc/Scene.i

# target to preprocess a source file
cfsrc/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Scene.cpp.i
.PHONY : cfsrc/Scene.cpp.i

cfsrc/Scene.s: cfsrc/Scene.cpp.s

.PHONY : cfsrc/Scene.s

# target to generate assembly for a file
cfsrc/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Scene.cpp.s
.PHONY : cfsrc/Scene.cpp.s

cfsrc/Text.o: cfsrc/Text.cpp.o

.PHONY : cfsrc/Text.o

# target to build an object file
cfsrc/Text.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Text.cpp.o
.PHONY : cfsrc/Text.cpp.o

cfsrc/Text.i: cfsrc/Text.cpp.i

.PHONY : cfsrc/Text.i

# target to preprocess a source file
cfsrc/Text.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Text.cpp.i
.PHONY : cfsrc/Text.cpp.i

cfsrc/Text.s: cfsrc/Text.cpp.s

.PHONY : cfsrc/Text.s

# target to generate assembly for a file
cfsrc/Text.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Text.cpp.s
.PHONY : cfsrc/Text.cpp.s

cfsrc/Timer.o: cfsrc/Timer.cpp.o

.PHONY : cfsrc/Timer.o

# target to build an object file
cfsrc/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Timer.cpp.o
.PHONY : cfsrc/Timer.cpp.o

cfsrc/Timer.i: cfsrc/Timer.cpp.i

.PHONY : cfsrc/Timer.i

# target to preprocess a source file
cfsrc/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Timer.cpp.i
.PHONY : cfsrc/Timer.cpp.i

cfsrc/Timer.s: cfsrc/Timer.cpp.s

.PHONY : cfsrc/Timer.s

# target to generate assembly for a file
cfsrc/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Timer.cpp.s
.PHONY : cfsrc/Timer.cpp.s

cfsrc/Transform.o: cfsrc/Transform.cpp.o

.PHONY : cfsrc/Transform.o

# target to build an object file
cfsrc/Transform.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Transform.cpp.o
.PHONY : cfsrc/Transform.cpp.o

cfsrc/Transform.i: cfsrc/Transform.cpp.i

.PHONY : cfsrc/Transform.i

# target to preprocess a source file
cfsrc/Transform.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Transform.cpp.i
.PHONY : cfsrc/Transform.cpp.i

cfsrc/Transform.s: cfsrc/Transform.cpp.s

.PHONY : cfsrc/Transform.s

# target to generate assembly for a file
cfsrc/Transform.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Transform.cpp.s
.PHONY : cfsrc/Transform.cpp.s

cfsrc/Utils.o: cfsrc/Utils.cpp.o

.PHONY : cfsrc/Utils.o

# target to build an object file
cfsrc/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Utils.cpp.o
.PHONY : cfsrc/Utils.cpp.o

cfsrc/Utils.i: cfsrc/Utils.cpp.i

.PHONY : cfsrc/Utils.i

# target to preprocess a source file
cfsrc/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Utils.cpp.i
.PHONY : cfsrc/Utils.cpp.i

cfsrc/Utils.s: cfsrc/Utils.cpp.s

.PHONY : cfsrc/Utils.s

# target to generate assembly for a file
cfsrc/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/Utils.cpp.s
.PHONY : cfsrc/Utils.cpp.s

cfsrc/sprite/AnimatedSprite.o: cfsrc/sprite/AnimatedSprite.cpp.o

.PHONY : cfsrc/sprite/AnimatedSprite.o

# target to build an object file
cfsrc/sprite/AnimatedSprite.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/AnimatedSprite.cpp.o
.PHONY : cfsrc/sprite/AnimatedSprite.cpp.o

cfsrc/sprite/AnimatedSprite.i: cfsrc/sprite/AnimatedSprite.cpp.i

.PHONY : cfsrc/sprite/AnimatedSprite.i

# target to preprocess a source file
cfsrc/sprite/AnimatedSprite.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/AnimatedSprite.cpp.i
.PHONY : cfsrc/sprite/AnimatedSprite.cpp.i

cfsrc/sprite/AnimatedSprite.s: cfsrc/sprite/AnimatedSprite.cpp.s

.PHONY : cfsrc/sprite/AnimatedSprite.s

# target to generate assembly for a file
cfsrc/sprite/AnimatedSprite.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/AnimatedSprite.cpp.s
.PHONY : cfsrc/sprite/AnimatedSprite.cpp.s

cfsrc/sprite/Sprite.o: cfsrc/sprite/Sprite.cpp.o

.PHONY : cfsrc/sprite/Sprite.o

# target to build an object file
cfsrc/sprite/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/Sprite.cpp.o
.PHONY : cfsrc/sprite/Sprite.cpp.o

cfsrc/sprite/Sprite.i: cfsrc/sprite/Sprite.cpp.i

.PHONY : cfsrc/sprite/Sprite.i

# target to preprocess a source file
cfsrc/sprite/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/Sprite.cpp.i
.PHONY : cfsrc/sprite/Sprite.cpp.i

cfsrc/sprite/Sprite.s: cfsrc/sprite/Sprite.cpp.s

.PHONY : cfsrc/sprite/Sprite.s

# target to generate assembly for a file
cfsrc/sprite/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/Sprite.cpp.s
.PHONY : cfsrc/sprite/Sprite.cpp.s

cfsrc/sprite/StaticSprite.o: cfsrc/sprite/StaticSprite.cpp.o

.PHONY : cfsrc/sprite/StaticSprite.o

# target to build an object file
cfsrc/sprite/StaticSprite.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/StaticSprite.cpp.o
.PHONY : cfsrc/sprite/StaticSprite.cpp.o

cfsrc/sprite/StaticSprite.i: cfsrc/sprite/StaticSprite.cpp.i

.PHONY : cfsrc/sprite/StaticSprite.i

# target to preprocess a source file
cfsrc/sprite/StaticSprite.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/StaticSprite.cpp.i
.PHONY : cfsrc/sprite/StaticSprite.cpp.i

cfsrc/sprite/StaticSprite.s: cfsrc/sprite/StaticSprite.cpp.s

.PHONY : cfsrc/sprite/StaticSprite.s

# target to generate assembly for a file
cfsrc/sprite/StaticSprite.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/sprite/StaticSprite.cpp.s
.PHONY : cfsrc/sprite/StaticSprite.cpp.s

cfsrc/world/StaticWorld.o: cfsrc/world/StaticWorld.cpp.o

.PHONY : cfsrc/world/StaticWorld.o

# target to build an object file
cfsrc/world/StaticWorld.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/StaticWorld.cpp.o
.PHONY : cfsrc/world/StaticWorld.cpp.o

cfsrc/world/StaticWorld.i: cfsrc/world/StaticWorld.cpp.i

.PHONY : cfsrc/world/StaticWorld.i

# target to preprocess a source file
cfsrc/world/StaticWorld.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/StaticWorld.cpp.i
.PHONY : cfsrc/world/StaticWorld.cpp.i

cfsrc/world/StaticWorld.s: cfsrc/world/StaticWorld.cpp.s

.PHONY : cfsrc/world/StaticWorld.s

# target to generate assembly for a file
cfsrc/world/StaticWorld.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/StaticWorld.cpp.s
.PHONY : cfsrc/world/StaticWorld.cpp.s

cfsrc/world/Tile.o: cfsrc/world/Tile.cpp.o

.PHONY : cfsrc/world/Tile.o

# target to build an object file
cfsrc/world/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/Tile.cpp.o
.PHONY : cfsrc/world/Tile.cpp.o

cfsrc/world/Tile.i: cfsrc/world/Tile.cpp.i

.PHONY : cfsrc/world/Tile.i

# target to preprocess a source file
cfsrc/world/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/Tile.cpp.i
.PHONY : cfsrc/world/Tile.cpp.i

cfsrc/world/Tile.s: cfsrc/world/Tile.cpp.s

.PHONY : cfsrc/world/Tile.s

# target to generate assembly for a file
cfsrc/world/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/Tile.cpp.s
.PHONY : cfsrc/world/Tile.cpp.s

cfsrc/world/TileComponent.o: cfsrc/world/TileComponent.cpp.o

.PHONY : cfsrc/world/TileComponent.o

# target to build an object file
cfsrc/world/TileComponent.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/TileComponent.cpp.o
.PHONY : cfsrc/world/TileComponent.cpp.o

cfsrc/world/TileComponent.i: cfsrc/world/TileComponent.cpp.i

.PHONY : cfsrc/world/TileComponent.i

# target to preprocess a source file
cfsrc/world/TileComponent.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/TileComponent.cpp.i
.PHONY : cfsrc/world/TileComponent.cpp.i

cfsrc/world/TileComponent.s: cfsrc/world/TileComponent.cpp.s

.PHONY : cfsrc/world/TileComponent.s

# target to generate assembly for a file
cfsrc/world/TileComponent.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/TileComponent.cpp.s
.PHONY : cfsrc/world/TileComponent.cpp.s

cfsrc/world/TiledWorld.o: cfsrc/world/TiledWorld.cpp.o

.PHONY : cfsrc/world/TiledWorld.o

# target to build an object file
cfsrc/world/TiledWorld.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/TiledWorld.cpp.o
.PHONY : cfsrc/world/TiledWorld.cpp.o

cfsrc/world/TiledWorld.i: cfsrc/world/TiledWorld.cpp.i

.PHONY : cfsrc/world/TiledWorld.i

# target to preprocess a source file
cfsrc/world/TiledWorld.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/TiledWorld.cpp.i
.PHONY : cfsrc/world/TiledWorld.cpp.i

cfsrc/world/TiledWorld.s: cfsrc/world/TiledWorld.cpp.s

.PHONY : cfsrc/world/TiledWorld.s

# target to generate assembly for a file
cfsrc/world/TiledWorld.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/TiledWorld.cpp.s
.PHONY : cfsrc/world/TiledWorld.cpp.s

cfsrc/world/World.o: cfsrc/world/World.cpp.o

.PHONY : cfsrc/world/World.o

# target to build an object file
cfsrc/world/World.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/World.cpp.o
.PHONY : cfsrc/world/World.cpp.o

cfsrc/world/World.i: cfsrc/world/World.cpp.i

.PHONY : cfsrc/world/World.i

# target to preprocess a source file
cfsrc/world/World.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/World.cpp.i
.PHONY : cfsrc/world/World.cpp.i

cfsrc/world/World.s: cfsrc/world/World.cpp.s

.PHONY : cfsrc/world/World.s

# target to generate assembly for a file
cfsrc/world/World.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/cfsrc/world/World.cpp.s
.PHONY : cfsrc/world/World.cpp.s

gamesrc/main.o: gamesrc/main.cpp.o

.PHONY : gamesrc/main.o

# target to build an object file
gamesrc/main.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/main.cpp.o
.PHONY : gamesrc/main.cpp.o

gamesrc/main.i: gamesrc/main.cpp.i

.PHONY : gamesrc/main.i

# target to preprocess a source file
gamesrc/main.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/main.cpp.i
.PHONY : gamesrc/main.cpp.i

gamesrc/main.s: gamesrc/main.cpp.s

.PHONY : gamesrc/main.s

# target to generate assembly for a file
gamesrc/main.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/main.cpp.s
.PHONY : gamesrc/main.cpp.s

gamesrc/myComponents/Entities/Destroyable.o: gamesrc/myComponents/Entities/Destroyable.cpp.o

.PHONY : gamesrc/myComponents/Entities/Destroyable.o

# target to build an object file
gamesrc/myComponents/Entities/Destroyable.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Entities/Destroyable.cpp.o
.PHONY : gamesrc/myComponents/Entities/Destroyable.cpp.o

gamesrc/myComponents/Entities/Destroyable.i: gamesrc/myComponents/Entities/Destroyable.cpp.i

.PHONY : gamesrc/myComponents/Entities/Destroyable.i

# target to preprocess a source file
gamesrc/myComponents/Entities/Destroyable.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Entities/Destroyable.cpp.i
.PHONY : gamesrc/myComponents/Entities/Destroyable.cpp.i

gamesrc/myComponents/Entities/Destroyable.s: gamesrc/myComponents/Entities/Destroyable.cpp.s

.PHONY : gamesrc/myComponents/Entities/Destroyable.s

# target to generate assembly for a file
gamesrc/myComponents/Entities/Destroyable.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Entities/Destroyable.cpp.s
.PHONY : gamesrc/myComponents/Entities/Destroyable.cpp.s

gamesrc/myComponents/Entities/exampleComponent.o: gamesrc/myComponents/Entities/exampleComponent.cpp.o

.PHONY : gamesrc/myComponents/Entities/exampleComponent.o

# target to build an object file
gamesrc/myComponents/Entities/exampleComponent.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Entities/exampleComponent.cpp.o
.PHONY : gamesrc/myComponents/Entities/exampleComponent.cpp.o

gamesrc/myComponents/Entities/exampleComponent.i: gamesrc/myComponents/Entities/exampleComponent.cpp.i

.PHONY : gamesrc/myComponents/Entities/exampleComponent.i

# target to preprocess a source file
gamesrc/myComponents/Entities/exampleComponent.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Entities/exampleComponent.cpp.i
.PHONY : gamesrc/myComponents/Entities/exampleComponent.cpp.i

gamesrc/myComponents/Entities/exampleComponent.s: gamesrc/myComponents/Entities/exampleComponent.cpp.s

.PHONY : gamesrc/myComponents/Entities/exampleComponent.s

# target to generate assembly for a file
gamesrc/myComponents/Entities/exampleComponent.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Entities/exampleComponent.cpp.s
.PHONY : gamesrc/myComponents/Entities/exampleComponent.cpp.s

gamesrc/myComponents/Tiles/exampleTileComponent.o: gamesrc/myComponents/Tiles/exampleTileComponent.cpp.o

.PHONY : gamesrc/myComponents/Tiles/exampleTileComponent.o

# target to build an object file
gamesrc/myComponents/Tiles/exampleTileComponent.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Tiles/exampleTileComponent.cpp.o
.PHONY : gamesrc/myComponents/Tiles/exampleTileComponent.cpp.o

gamesrc/myComponents/Tiles/exampleTileComponent.i: gamesrc/myComponents/Tiles/exampleTileComponent.cpp.i

.PHONY : gamesrc/myComponents/Tiles/exampleTileComponent.i

# target to preprocess a source file
gamesrc/myComponents/Tiles/exampleTileComponent.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Tiles/exampleTileComponent.cpp.i
.PHONY : gamesrc/myComponents/Tiles/exampleTileComponent.cpp.i

gamesrc/myComponents/Tiles/exampleTileComponent.s: gamesrc/myComponents/Tiles/exampleTileComponent.cpp.s

.PHONY : gamesrc/myComponents/Tiles/exampleTileComponent.s

# target to generate assembly for a file
gamesrc/myComponents/Tiles/exampleTileComponent.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myComponents/Tiles/exampleTileComponent.cpp.s
.PHONY : gamesrc/myComponents/Tiles/exampleTileComponent.cpp.s

gamesrc/myCore/core.o: gamesrc/myCore/core.cpp.o

.PHONY : gamesrc/myCore/core.o

# target to build an object file
gamesrc/myCore/core.cpp.o:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myCore/core.cpp.o
.PHONY : gamesrc/myCore/core.cpp.o

gamesrc/myCore/core.i: gamesrc/myCore/core.cpp.i

.PHONY : gamesrc/myCore/core.i

# target to preprocess a source file
gamesrc/myCore/core.cpp.i:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myCore/core.cpp.i
.PHONY : gamesrc/myCore/core.cpp.i

gamesrc/myCore/core.s: gamesrc/myCore/core.cpp.s

.PHONY : gamesrc/myCore/core.s

# target to generate assembly for a file
gamesrc/myCore/core.cpp.s:
	$(MAKE) -f CMakeFiles/closedFrameworks.dir/build.make CMakeFiles/closedFrameworks.dir/gamesrc/myCore/core.cpp.s
.PHONY : gamesrc/myCore/core.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... closedFrameworks"
	@echo "... CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.6.1/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... cfsrc/Animator.o"
	@echo "... cfsrc/Animator.i"
	@echo "... cfsrc/Animator.s"
	@echo "... cfsrc/BaseCore.o"
	@echo "... cfsrc/BaseCore.i"
	@echo "... cfsrc/BaseCore.s"
	@echo "... cfsrc/BoxCollider.o"
	@echo "... cfsrc/BoxCollider.i"
	@echo "... cfsrc/BoxCollider.s"
	@echo "... cfsrc/Client.o"
	@echo "... cfsrc/Client.i"
	@echo "... cfsrc/Client.s"
	@echo "... cfsrc/Collider.o"
	@echo "... cfsrc/Collider.i"
	@echo "... cfsrc/Collider.s"
	@echo "... cfsrc/Collision.o"
	@echo "... cfsrc/Collision.i"
	@echo "... cfsrc/Collision.s"
	@echo "... cfsrc/Component.o"
	@echo "... cfsrc/Component.i"
	@echo "... cfsrc/Component.s"
	@echo "... cfsrc/Entity.o"
	@echo "... cfsrc/Entity.i"
	@echo "... cfsrc/Entity.s"
	@echo "... cfsrc/Graphics.o"
	@echo "... cfsrc/Graphics.i"
	@echo "... cfsrc/Graphics.s"
	@echo "... cfsrc/Image.o"
	@echo "... cfsrc/Image.i"
	@echo "... cfsrc/Image.s"
	@echo "... cfsrc/Input.o"
	@echo "... cfsrc/Input.i"
	@echo "... cfsrc/Input.s"
	@echo "... cfsrc/ResourceManager.o"
	@echo "... cfsrc/ResourceManager.i"
	@echo "... cfsrc/ResourceManager.s"
	@echo "... cfsrc/RigidBody.o"
	@echo "... cfsrc/RigidBody.i"
	@echo "... cfsrc/RigidBody.s"
	@echo "... cfsrc/Runner.o"
	@echo "... cfsrc/Runner.i"
	@echo "... cfsrc/Runner.s"
	@echo "... cfsrc/Scene.o"
	@echo "... cfsrc/Scene.i"
	@echo "... cfsrc/Scene.s"
	@echo "... cfsrc/Text.o"
	@echo "... cfsrc/Text.i"
	@echo "... cfsrc/Text.s"
	@echo "... cfsrc/Timer.o"
	@echo "... cfsrc/Timer.i"
	@echo "... cfsrc/Timer.s"
	@echo "... cfsrc/Transform.o"
	@echo "... cfsrc/Transform.i"
	@echo "... cfsrc/Transform.s"
	@echo "... cfsrc/Utils.o"
	@echo "... cfsrc/Utils.i"
	@echo "... cfsrc/Utils.s"
	@echo "... cfsrc/sprite/AnimatedSprite.o"
	@echo "... cfsrc/sprite/AnimatedSprite.i"
	@echo "... cfsrc/sprite/AnimatedSprite.s"
	@echo "... cfsrc/sprite/Sprite.o"
	@echo "... cfsrc/sprite/Sprite.i"
	@echo "... cfsrc/sprite/Sprite.s"
	@echo "... cfsrc/sprite/StaticSprite.o"
	@echo "... cfsrc/sprite/StaticSprite.i"
	@echo "... cfsrc/sprite/StaticSprite.s"
	@echo "... cfsrc/world/StaticWorld.o"
	@echo "... cfsrc/world/StaticWorld.i"
	@echo "... cfsrc/world/StaticWorld.s"
	@echo "... cfsrc/world/Tile.o"
	@echo "... cfsrc/world/Tile.i"
	@echo "... cfsrc/world/Tile.s"
	@echo "... cfsrc/world/TileComponent.o"
	@echo "... cfsrc/world/TileComponent.i"
	@echo "... cfsrc/world/TileComponent.s"
	@echo "... cfsrc/world/TiledWorld.o"
	@echo "... cfsrc/world/TiledWorld.i"
	@echo "... cfsrc/world/TiledWorld.s"
	@echo "... cfsrc/world/World.o"
	@echo "... cfsrc/world/World.i"
	@echo "... cfsrc/world/World.s"
	@echo "... gamesrc/main.o"
	@echo "... gamesrc/main.i"
	@echo "... gamesrc/main.s"
	@echo "... gamesrc/myComponents/Entities/Destroyable.o"
	@echo "... gamesrc/myComponents/Entities/Destroyable.i"
	@echo "... gamesrc/myComponents/Entities/Destroyable.s"
	@echo "... gamesrc/myComponents/Entities/exampleComponent.o"
	@echo "... gamesrc/myComponents/Entities/exampleComponent.i"
	@echo "... gamesrc/myComponents/Entities/exampleComponent.s"
	@echo "... gamesrc/myComponents/Tiles/exampleTileComponent.o"
	@echo "... gamesrc/myComponents/Tiles/exampleTileComponent.i"
	@echo "... gamesrc/myComponents/Tiles/exampleTileComponent.s"
	@echo "... gamesrc/myCore/core.o"
	@echo "... gamesrc/myCore/core.i"
	@echo "... gamesrc/myCore/core.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

