all:
	@cd ./Basic && make
	@cd ./BasicComponent && make
	@cd ./BlockSpawn && make
	@cd ./CustomUpdateDraw && make
	@cd ./PongGame && make
	@cd ./SpaceInvaders && make
	@cd ./Breakout && make
	@cd ./TextEntity && make
	@cd ./TextRaw && make
	@cd ./AudioRaw && make
	@cd ./AudioEntity && make
clean:
	@cd ./Basic && make clean
	@cd ./BasicComponent && make clean
	@cd ./CustomUpdateDraw && make clean
	@cd ./BlockSpawn && make clean
	@cd ./xCodeExample && make clean
	@cd ./PongGame && make clean
	@cd ./SpaceInvaders && make clean
	@cd ./Breakout && make clean
	@cd ./TextEntity && make clean
	@cd ./TextRaw && make clean
	@cd ./AudioRaw && make clean
	@cd ./AudioEntity && make clean
