all:
	@cd ./Basic && make
	@cd ./BasicComponent && make
	@cd ./CustomUpdateDraw && make
	@cd ./PongGame && make
	@cd ./SpaceInvaders && make
	@cd ./Breakout && make
clean:
	@cd ./Basic && make clean
	@cd ./BasicComponent && make clean
	@cd ./CustomUpdateDraw && make clean
	@cd ./xCodeExample && make clean
	@cd ./PongGame && make clean
	@cd ./SpaceInvaders && make clean
	@cd ./Breakout && make clean